### ISSUE TITLE
Unicode in Application Names

### ISSUE THREAD

**Issue by ecrist** [brysontyrrell/PatchServer#38]
The script doesn't currently support unicode characters in the application names.  Our first instance of this is Übersicht.  We've tried munging it but it's very quickly a mess.

```
ecrist@mackerel322:~/Patch-Starter-Script-> python patchstarter.py -o . --patch-only /Applications/Übersicht.app
Traceback (most recent call last):
  File "patchstarter.py", line 263, in <module>
    main()
  File "patchstarter.py", line 100, in main
    filename = '{}-patch.json'.format(app_id)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0308' in position 1: ordinal not in range(128)
```

**Comment by ecrist** [comment]
👉🏻 

Poke?
